import type { APIRoute } from "astro";
import { requireAdminAuth } from "../../../lib/api/requireAuth";
import { documents, documentChunks } from "../../../lib/db/schema";
import { eq, count } from "drizzle-orm";

/**
 * POST /api/admin/sync-docs
 *
 * In production, this syncs repo docs from a prebuild manifest into Supabase
 * storage and kb_queue. The self-hosted version reports on document counts
 * from the local documents/document_chunks tables.
 *
 * Full sync functionality requires:
 * - _docs-manifest.json (generated by prebuild)
 * - kb_projects, kb_folders, kb_queue tables (not in self-hosted schema)
 * - Supabase storage bucket (kb-files)
 */
export const POST: APIRoute = async (context) => {
  const { user, db, error } = await requireAdminAuth(context);
  if (error) return error;

  try {
    // Report current document counts from local schema
    const [docCountRow] = await db.select({ value: count() }).from(documents);
    const [chunkCountRow] = await db.select({ value: count() }).from(documentChunks);

    const docCount = docCountRow?.value ?? 0;
    const chunkCount = chunkCountRow?.value ?? 0;

    return new Response(
      JSON.stringify({
        synced: 0,
        skipped: 0,
        total: 0,
        local_documents: docCount,
        local_chunks: chunkCount,
        message:
          "Full doc sync requires kb_projects/kb_queue tables and Supabase storage. " +
          "Use the documents table for self-hosted document management.",
      }),
      {
        status: 200,
        headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
      },
    );
  } catch (err: unknown) {
    console.error("[sync-docs POST]", err instanceof Error ? err.message : err);
    return new Response(JSON.stringify({ error: "Database error" }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }
};
