export interface Suggestion {
  text: string;
  href?: string;
}

interface Props {
  suggestions: Suggestion[];
}

// Patterns that indicate an urgent suggestion. These are matched case-insensitively
// against suggestion text generated by buildSuggestions() in dashboardUtils.ts.
// If buildSuggestions() wording changes, these patterns may need updating.
// A more robust approach would be to add an `urgency` field to the Suggestion type
// and set it at the source in buildSuggestions().
const URGENT_PATTERNS = /\b(fail(ing|ed|s)?|declining|no data|error|offline|unreachable)\b/i;

export default function SuggestionsPanel({ suggestions }: Props) {
  if (suggestions.length === 0) return null;

  const hasUrgent = suggestions.some((s) => URGENT_PATTERNS.test(s.text));

  return (
    <div className={`admin-card p-5 ${hasUrgent ? "amber-border-glow" : ""}`}>
      <div className="flex items-center gap-2 mb-3">
        <span
          className="text-[14px] font-mono font-medium text-ink-tertiary uppercase tracking-[0.08em]"
          title="Data-driven improvement suggestions"
        >
          Suggestions
        </span>
        <span className="inline-flex items-center justify-center min-w-[20px] h-5 px-1.5 rounded-full text-[14px] font-medium tabular-nums bg-gold/15 text-gold">
          {suggestions.length}
        </span>
      </div>
      <div className="space-y-2">
        {suggestions.map((s, i) => (
          <div
            key={i}
            className={`flex items-start sm:items-center gap-3 text-[16px] sm:text-[18px] leading-relaxed ${
              i === 0 ? "font-medium" : ""
            }`}
          >
            <span className="text-gold shrink-0">*</span>
            <span className={i === 0 ? "text-ink" : "text-ink-secondary"}>
              {s.text}
            </span>
            {s.href && (
              <a
                href={s.href}
                target="_blank"
                rel="noopener noreferrer"
                className="ml-auto text-ink-tertiary hover:text-gold transition-colors shrink-0"
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" />
                </svg>
              </a>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
